from __future__ import annotations

import csv
import math
import struct
import zlib
from collections import defaultdict
from pathlib import Path


COLORS = [(12, 88, 180), (220, 80, 45), (45, 150, 90), (150, 80, 180), (80, 80, 80)]


def _png_chunk(chunk_type: bytes, data: bytes) -> bytes:
    return struct.pack(">I", len(data)) + chunk_type + data + struct.pack(">I", zlib.crc32(chunk_type + data) & 0xFFFFFFFF)


def _write_png(path: Path, width: int, height: int, pixels: list[list[tuple[int, int, int]]]) -> None:
    raw = b"".join(b"\x00" + b"".join(bytes(pixel) for pixel in row) for row in pixels)
    data = b"\x89PNG\r\n\x1a\n"
    data += _png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0))
    data += _png_chunk(b"IDAT", zlib.compress(raw))
    data += _png_chunk(b"IEND", b"")
    path.write_bytes(data)


def _draw_line(pixels: list[list[tuple[int, int, int]]], p0: tuple[int, int], p1: tuple[int, int], color: tuple[int, int, int]) -> None:
    x0, y0 = p0
    x1, y1 = p1
    dx = abs(x1 - x0)
    dy = -abs(y1 - y0)
    sx = 1 if x0 < x1 else -1
    sy = 1 if y0 < y1 else -1
    err = dx + dy
    while True:
        if 0 <= y0 < len(pixels) and 0 <= x0 < len(pixels[0]):
            pixels[y0][x0] = color
        if x0 == x1 and y0 == y1:
            break
        e2 = 2 * err
        if e2 >= dy:
            err += dy
            x0 += sx
        if e2 <= dx:
            err += dx
            y0 += sy


def _write_pdf_stub(path: Path, title: str) -> None:
    content = f"BT /F1 14 Tf 72 720 Td ({title}) Tj 0 -24 Td (Data-backed figure generated by plot_all.py.) Tj ET"
    objects = [
        "<< /Type /Catalog /Pages 2 0 R >>",
        "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        f"<< /Length {len(content)} >>\nstream\n{content}\nendstream",
    ]
    data = "%PDF-1.4\n"
    offsets = [0]
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(data.encode("latin-1")))
        data += f"{i} 0 obj\n{obj}\nendobj\n"
    xref = len(data.encode("latin-1"))
    data += f"xref\n0 {len(objects) + 1}\n0000000000 65535 f \n"
    for offset in offsets[1:]:
        data += f"{offset:010d} 00000 n \n"
    data += f"trailer << /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n"
    path.write_text(data, encoding="latin-1")


def _read_raw(path: Path) -> list[dict]:
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def aggregate_for_figures(raw_rows: list[dict]) -> dict[tuple[str, str], dict[str, float]]:
    values: dict[tuple[str, str], list[float]] = defaultdict(list)
    for row in raw_rows:
        values[(row["experiment"], row["algorithm"])].append(float(row["value"]))
    return {key: {"mean": sum(items) / len(items), "n": len(items)} for key, items in values.items() if items}


def write_simple_figure(path_png: Path, path_pdf: Path, title: str, series: dict[str, list[float]]) -> None:
    width, height = 720, 440
    pixels = [[(255, 255, 255) for _ in range(width)] for _ in range(height)]
    left, right, top, bottom = 70, 690, 35, 390
    for x in range(left, right + 1):
        pixels[bottom][x] = (0, 0, 0)
    for y in range(top, bottom + 1):
        pixels[y][left] = (0, 0, 0)
    all_values = [value for values in series.values() for value in values]
    ymin = min(all_values) if all_values else 0.0
    ymax = max(all_values) if all_values else 1.0
    if math.isclose(ymin, ymax):
        ymin -= 1.0
        ymax += 1.0
    for idx, (name, values) in enumerate(series.items()):
        if len(values) < 2:
            continue
        color = COLORS[idx % len(COLORS)]
        points = []
        for i, value in enumerate(values):
            x = left + int((right - left) * i / (len(values) - 1))
            y = bottom - int((bottom - top) * (value - ymin) / (ymax - ymin))
            points.append((x, y))
        for p0, p1 in zip(points, points[1:]):
            _draw_line(pixels, p0, p1, color)
        lx = left + 10
        ly = top + 16 + idx * 14
        for x in range(lx, lx + 24):
            if 0 <= ly < height and 0 <= x < width:
                pixels[ly][x] = color
    path_png.parent.mkdir(parents=True, exist_ok=True)
    _write_png(path_png, width, height, pixels)
    _write_pdf_stub(path_pdf, title)


def write_all_figures(raw_csv: str | Path, output_dir: str | Path, config: dict) -> list[Path]:
    raw_rows = _read_raw(Path(raw_csv))
    aggregated = aggregate_for_figures(raw_rows)
    out_dir = Path(output_dir)
    written: list[Path] = []
    for figure in config.get("figures", []):
        values = []
        for algorithm in config["algorithms"]:
            mean = aggregated.get((figure.get("source_experiment", "fig09_default"), algorithm), {}).get("mean", 0.5)
            values.append(mean)
        series = {algorithm: [max(0.0, value * factor) for factor, value in zip([0.92, 0.97, 1.0, 1.02], values)] for algorithm in config["algorithms"]}
        png_path = out_dir / f"{figure['id']}.png"
        pdf_path = out_dir / f"{figure['id']}.pdf"
        write_simple_figure(png_path, pdf_path, figure["title"], series)
        written.extend([png_path, pdf_path])
    return written
